# -*- coding: utf-8 -*-
"""
/***************************************************************************
 opencratertool
                                 A QGIS plugin
 A tool for crater size-frequency measurements
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-08-14
        copyright            : (C) 2022 by Thomas Heyer
        email                : thomas.heyer@uni-muenster.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load opencratertool class from file opencratertool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .opencratertool import opencratertool
    return opencratertool(iface)
